### ISSUE TITLE
Handling of Optional Parameters in OpenIdClient and OIDC Flows

### ISSUE THREAD

**Issue by timhallmann** [fsinfuhh/py_simple_openid_connect#24]
The OpenIdClient and the OIDC flows do not expose most of the optional parameters supported by the protocol, such as `state`, `nonce` or `prompt`.

In PR #23, the additional parameters have been added to all relevant interfaces. Is the intention to eventually add all parameters directly to the function signatures, as in the following example?

```
class OpenIdClient:
    def start_authentication(
        state: Optional[str] = None,
        response_mode: Optional[str] = None,
        nonce: Optional[str] = None,
        display: Optional[List[str]] = None,
        prompt: Optional[List[str]] = None,
        max_age: Optional[int] = None,
        ui_locales: Optional[List[str]] = None,
        id_token_hint: Optional[str] = None,
        acr_values: Optional[List[str]] = None,
        code_challenge: Optional[str] = None,
        code_challenge_method: Optional[Literal['S256']] = None,
    ):
        ...
```

Or would an alternative be preferable? For example, separate models:

```
class AuthenticationRequestParameters(OpenidBaseModel):
    model_config = ConfigDict(extra="allow")

    state: Optional[str] = None
    response_mode: Optional[str] = None
    nonce: Optional[str] = None
    display: Optional[List[str]] = None
    prompt: Optional[List[str]] = None
    max_age: Optional[int] = None
    ui_locales: Optional[List[str]] = None
    id_token_hint: Optional[str] = None
    acr_values: Optional[List[str]] = None
    code_challenge: Optional[str] = None
    code_challenge_method: Optional[Literal['S256']] = None

class AuthenticationRequest(AuthenticationRequestParameters):
    scope: str
    response_type: str
    client_id: str
    redirect_uri: str

class OpenIdClient:
    def start_authentication(parameters: Optional[AuthenticationRequestParameters] = None):
        ...
```

While I prefer the first approach for its simplicity, it does require quite a bit of duplication in function signatures and is a bit cumbersome. If the first approach is acceptable, I can create pull requests for `state`, `nonce`, and `prompt`, which I have already implemented.

**Comment by ftsell** [comment]
Yes, adding optional parameters to the function  signatures is the preferred way. I agree that doing it this way is a bit cumbersome to maintain but in my opinion, it makes these functions easier to use. 

If you have already implemented it, a PR would indeed be appreciated. I'm planning to merge the mentioned PR #23 soon though so you might need to do a rebase.

**Comment by timhallmann** [comment]
Great!

I'll create a PR once #23 that is merged.
